# python arthimetic operation
a = int(input("Enter the first number"))
b = int(input("Enter the second number"))
print(a + b)
print( a-b)
print(a * b)
a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Floor Division:", a // b)
print("Modulus:", a % b)
print("Exponent:", a ** b)
